app/models/question.py
from app.extensions import db
from datetime import datetime
from app.models.user import User
from app.models.theme import Theme


class Question(db.Model):
    __tablename__ = 'questions'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    body = db.Column(db.Text, nullable=False)
    likes = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey(User.id), nullable=False)
    themes_id = db.Column(db.Integer, db.ForeignKey(Theme.id), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(
        db.DateTime, default=datetime.now, onupdate=datetime.now)
    
    answers = db.relationship('Answer', backref='question')
    reports = db.relationship('Question_report', backref='question')
    

app/blueprints/dashboard/question/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard_question', __name__)

from app.blueprints.dashboard.question import routes

app/blueprints/dashboard/question/routes.py
from app.blueprints.dashboard.question import bp
from flask import render_template
from app.controllers.dashboard.dashboard_questionController import DashboardQuetionController
from flask_login import login_required


@bp.get('/dashboard/questions/')
def index():
    return DashboardQuetionController.index()

app/blueprints/question/__init__.py
from flask import Blueprint

bp = Blueprint('question', __name__)

from app.blueprints.question import routes

app/blueprints/question/routes.py
from app.blueprints.question import bp
from app.controllers.questionController import QuestionController
from flask_login import login_required


@bp.get('/questions/')
@bp.get('/questions/<id>')
def index(id=0):
    return QuestionController.index(id)

@bp.get('/question/create/')
def create():
    return QuestionController.create()

@bp.post('/question/store/')
def store():
    return QuestionController.store()

@bp.get('/question/<int:id>')
def view_question(id):
    return QuestionController.view_question(id)

app/controllers/questionController.py
from flask import render_template, redirect, request, url_for
from app.blueprints.question.form import QuestionForm
from app.repositories.themeRepository import ThemeRepository
from app.repositories.academic_subjectRepository import AcademicSubjectRepository
from app.repositories.questionRepository import QuestionRepository
from app.repositories.answerRepository import AnswerRepository
from app.utils import format_data
from flask_login import login_user, current_user, logout_user


class QuestionController():
    def index(id):
        if id == 0:
            sub = "Все"
            questions = QuestionRepository.all_question()
        else:
            sub = AcademicSubjectRepository.get_academic_subject_by_id(id).title
            questions = QuestionRepository.quetion_by_theme(AcademicSubjectRepository.get_academic_subject_by_id(id).id)
        subjects = AcademicSubjectRepository.academic_subject_choices()
        q_dates = format_data(questions)

        return render_template('question/index.html.jinja', sub=sub, subjects=subjects, questions=questions, q_dates=q_dates)
    
    def create():
        form = QuestionForm('/question/create')
        form.theme.choices = [(s.id, f'{s.academic_subject.title} {s.academic_class.title}, {s.title}')
                              for s in ThemeRepository.theme_choices()]
        return render_template('question/create.html.jinja', form=form)
    
    def store():
        title = request.form.get('title')
        body = request.form.get('body')
        likes = 0
        user_id = current_user.id
        themes_id = request.form.get('theme')

        question = QuestionRepository.store_question(title, body, likes, user_id, themes_id)

        return redirect(f'/question/{question.id}')

    def view_question(id):
        question = QuestionRepository.get_question_by_id(id)
        answers = AnswerRepository.get_answer_to_question(id)
        q_dates = format_data([question])[0]

        return render_template('question/view.html.jinja', question=question, answers=answers, q_dates=q_dates)

app/templates/question/create.html.jinja
{% extends 'layouts/base.html.jinja' %}
{% from "macros/form/form_wrapper.html.jinja" import form_wrapper with context %}
{% from "macros/form/form_input.html.jinja" import form_input with context %}
{% from "macros/form/form_submit.html.jinja" import form_submit with context %}
{% from "layouts/particles/header.html.jinja" import header_part with context %}

{% block header %}
{{ header_part(False, 'question_create')}}
{% endblock %}

{% block content %}
    <h1 class="text-4xl mb-8 text-center font-semibold text-blue-950">Задать вопрос</h1>
    {% call form_wrapper(action=url_for('question.store'))%} 
        {{form.hidden_tag()}}
        {{ form_input(item=form.title)}}
        {{ form_input(item=form.body)}}
        {{ form_input(item=form.theme)}}
        {{ form_submit(text='Задать вопрос')}}
    {% endcall %}
        {{ ckeditor.load(custom_url=url_for('static', filename='ckeditor/ckeditor.js')) }}
        {{ ckeditor.config(name='body') }}
{% endblock %}

 

app/templates/question/index.html.jinja
{% extends 'layouts/base.html.jinja' %}
{% from "layouts/particles/header.html.jinja" import header_part with context %}
{% from "macros/items/question_items.html.jinja" import question_item with context %}

{% block header %}
{{ header_part(False, 'question', sub, subjects)}}
{% endblock %}
{% block content %}
<h1 class="text-4xl mb-8 text-center font-semibold text-blue-950">Вопросы: {{sub}}</h1>
{{question_item(qestions, q_dates)}}
{% endblock %}

app/templates/question/view.html.jinja
{% extends 'layouts/base.html.jinja' %}
{% from "layouts/particles/header.html.jinja" import header_part with context %}

{% block header %}
{{ header_part(False)}}
{%endblock%}
{% block content %}
<div class="w-4/5 bg-blue-200 p-8 rounded-xl relative text-blue-950 m-auto">
<a href="{{url_for('profile.index', id=question.user.id)}}">
<div class="w-24 h-24"><img class="rounded-full" src="{{url_for('static', filename='avatars/'+ question.user.avatar ) }}"></div>
</a>
<div class="text-2xl font-semibold absolute left-36 top-8">{{question.user.nickname}}</div>
<div class="absolute text-lg left-36 top-16">{{q_dates}} {{question.theme.academic_subject.title}} {{question.theme.academic_class.title}} класс {{question.theme.title}}</div>
{% if answers %}
<div class="text-xl bg-blue-300 p-2 rounded-full inline-block font-medium absolute right-12 top-6">Ответ дан</div>
{% endif %}
<div class="text-4xl ml-4 mt-6 font-semibold">{{question.title}}</div>
<div class="text-3xl ml-6 mt-8">{{question.body}}</div>
<a href="{{url_for('answer.create', id=question.id)}}" class="text-2xl p-4 border-blue-950 rounded-full mt-8 inline-block border-2">
+ Добавить ответ <span class="text-xl font-light">+25б.</span>
</a>
</div>
<div class="w-4/5 bg-blue-200 p-8 rounded-xl relative text-blue-950 m-auto mt-12">
<div class="text-3xl font-semibold mb-8">Ответы</div>
{% for answer in answers%}
<div class="relative mb-12">
<a href="{{url_for('profile.index', id=answer.user.id)}}">
<div class="w-16 h-16 inline-block"><img class="rounded-full" src="{{url_for('static', filename='avatars/'+ answer.user.avatar ) }}"></div>
</a>
<div class="text-xl font-semibold absolute left-20 top-1">{{answer.user.nickname}}</div>
<div class="text-lg font-normal absolute left-20 top-8">{{answer.user.rating.title}}</div>
<div class="text-2xl ml-20 mt-8">{{answer.body}}</div>
</div>
{% endfor %}
</div>
{%endblock%}