app/blueprints/dashboard/academic_class/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard_academic_class', __name__)

from app.blueprints.dashboard.academic_class import routes

app/blueprints/dashboard/academic_class/routes.py
from app.blueprints.dashboard.academic_class import bp
from flask import render_template
from app.controllers.dashboard.dashboard_academic_classController import DashboardAcademicClassController
from flask_login import login_required


@bp.get('/dashboard/academic_classes/')
@bp.get('/dashboard/academic_classes/<int:page>/')
@login_required
def index(page=1):
    return DashboardAcademicClassController.index(page)

@bp.get('/dashboard/academic_classes/create/')
def create():
    return DashboardAcademicClassController.create()

@bp.post('/dashboard/academic_classes/store/')
def store():
    return DashboardAcademicClassController.store()

@bp.get('/dashboard/academic_classes/edit/<int:id>/')
def edit(id):
    return DashboardAcademicClassController.edit(id)

@bp.post('/dashboard/academic_classes/update/')
def update():
    return DashboardAcademicClassController.update()

app/blueprints/dashboard/academic_subject/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard_academic_subject', __name__)

from app.blueprints.dashboard.academic_subject import routes

app/blueprints/dashboard/academic_subject/routes.py
from app.blueprints.dashboard.academic_subject import bp
from flask import render_template
from app.controllers.dashboard.dashboard_academic_subjectController import DashboardAcademicSubjectController
from flask_login import login_required


@bp.get('/dashboard/academic_subjects/')
@bp.get('/dashboard/academic_subjects/<int:page>/')
def index(page=1):
    return DashboardAcademicSubjectController.index(page)

@bp.get('/dashboard/academic_subjects/create/')
def create():
    return DashboardAcademicSubjectController.create()

@bp.post('/dashboard/academic_subjects/store/')
def store():
    return DashboardAcademicSubjectController.store()

@bp.get('/dashboard/academic_subjects/edit/<int:id>/')
def edit(id):
    return DashboardAcademicSubjectController.edit(id)

@bp.post('/dashboard/academic_subjects/update/')
def update():
    return DashboardAcademicSubjectController.update()

app/blueprints/dashboard/question/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard_question', __name__)

from app.blueprints.dashboard.question import routes

app/blueprints/dashboard/question/routes.py
from app.blueprints.dashboard.question import bp
from flask import render_template
from app.controllers.dashboard.dashboard_questionController import DashboardQuetionController
from flask_login import login_required


@bp.get('/dashboard/questions/')
def index():
    return DashboardQuetionController.index()

app/blueprints/dashboard/rating/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard_rating', __name__)

from app.blueprints.dashboard.rating import routes

app/blueprints/dashboard/rating/routes.py
from app.blueprints.dashboard.rating import bp
from flask import render_template
from app.controllers.dashboard.dashboard_ratingController import DashboardRatingController


@bp.get('/dashboard/rating/')
@bp.get('/dashboard/rating/<int:page>/')
def index(page=1):
    return DashboardRatingController.index(page)

@bp.get('/dashboard/rating/create/')
def create():
    return DashboardRatingController.create()

@bp.post('/dashboard/rating/store/')
def store():
    return DashboardRatingController.store()

@bp.get('/dashboard/rating/edit/<int:id>/')
def edit(id):
    return DashboardRatingController.edit(id)

@bp.post('/dashboard/rating/update/')
def update():
    return DashboardRatingController.update()

app/blueprints/dashboard/role/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard_role', __name__)

from app.blueprints.dashboard.role import routes

app/blueprints/dashboard/role/routes.py
from app.blueprints.dashboard.role import bp
from app.controllers.dashboard.dashboard_roleController import DashboardRoleController


@bp.get('/dashboard/role/')
@bp.get('/dashboard/role/<int:page>/')
def index(page=1):
    return DashboardRoleController.index(page)

@bp.get('/dashboard/role/create/')
def create():
    return DashboardRoleController.create()

@bp.post('/dashboard/role/store/')
def store():
    return DashboardRoleController.store()

@bp.get('/dashboard/role/edit/<int:id>/')
def edit(id):
    return DashboardRoleController.edit(id)

@bp.post('/dashboard/role/update/')
def update():
    return DashboardRoleController.update()

app/blueprints/dashboard/theme/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard_theme', __name__)

from app.blueprints.dashboard.theme import routes

app/blueprints/dashboard/theme/routes.py
from app.blueprints.dashboard.theme import bp
from app.controllers.dashboard.dashboard_themeController import DashboardThemeController
from flask_login import login_required


@bp.get('/dashboard/theme/')
@bp.get('/dashboard/theme/<int:page>/')
def index(page=1):
    return DashboardThemeController.index(page)

@bp.get('/dashboard/theme/create/')
def create():
    return DashboardThemeController.create()

@bp.post('/dashboard/theme/store/')
def store():
    return DashboardThemeController.store()

@bp.get('/dashboard/theme/edit/<int:id>/')
def edit(id):
    return DashboardThemeController.edit(id)

@bp.post('/dashboard/theme/update/')
def update():
    return DashboardThemeController.update()

app/templates/dashboard/academic_class/create.html.jinja
{% extends 'layouts/dashboard.html.jinja' %}
{% from "macros/form/form_wrapper.html.jinja" import form_wrapper with context %}
{% from "macros/form/form_input.html.jinja" import form_input with context %}
{% from "macros/form/form_submit.html.jinja" import form_submit with context %}

{% block content %}
    <h1 class="text-4xl mb-8 text-center font-semibold text-blue-950">Создать класс</h1>
    {% call form_wrapper(action=url_for('dashboard_academic_class.store'))%} 
        {{form.hidden_tag()}}
        {{ form_input(item=form.title)}}
        {{ form_submit(text='Создать')}}
    {% endcall %}

{% endblock %}

app/templates/dashboard/academic_class/edit.html.jinja
{% extends 'layouts/dashboard.html.jinja' %}
{% from "macros/form/form_wrapper.html.jinja" import form_wrapper with context %}
{% from "macros/form/form_input.html.jinja" import form_input with context %}
{% from "macros/form/form_submit.html.jinja" import form_submit with context %}

{% block content %}
    <h1 class="text-4xl mb-8 text-center font-semibold text-blue-950">Редактирование класса ID: {{academic_class.id}}</h1>
    {% call form_wrapper(action=url_for('dashboard_academic_class.update'))%} 
        {{form.hidden_tag()}}
        <input type="hidden" name="id" value="{{ academic_class.id }}" />
        {{ form_input(item=form.title, value=academic_class.title)}}
        {{ form_submit(text='Изменить')}}
    {% endcall %}

{% endblock %}

app/templates/dashboard/academic_class/index.html.jinja
{% extends 'layouts/dashboard.html.jinja' %}
{% from "macros/items/items.html.jinja" import item with context %}


{% block content %}
    <h1 class="text-5xl mb-8 text-center font-semibold text-blue-950 hover:underline"><a href="{{url_for('dashboard_academic_class.create')}}">Классы</a></h1>
    {% for academic_class in academic_classes %}
    {{item('dashboard_academic_class', ['ID', 'Название'], [academic_class.id, academic_class.title], 2)}}
    {% endfor %}
{% endblock %}